### PR TITLE
fix(GuildQueuePlayerNode): fix stream error

### LINKED ISSUE #1653: Player doesn't skip unplayable track even with skipOnNoStream option enabled
**Describe the bug**
Discord-player throws an error `Could not extract stream for this track` when playing age restricted video from YouTube.
After adding `skipOnNoStream: true` to the `nodeOptions` another error is emitted: 
`Play request received but track was not provided`

**To Reproduce**
-Play any age restricted video from YouTube, for example [https://www.youtube.com/watch?v=nwnq7o99obo](url)

**Expected behavior**

After adding `skipOnNoStream: true` discord-player should skip the unplayable song.

**Screenshots**

image
image

**Please complete the following information:**
 - Node Version: 18.14.2
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

### PR DESCRIPTION
**Pull request by Abish-x-lethal**
## Changes
closes #1653
## Status

- [x] These changes have been tested and formatted properly.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

### CODE REVIEW

File: packages/discord-player/src/Structures/GuildQueuePlayerNode.ts [hunk 1]
```diff
@@ -395,7 +395,8 @@ export class GuildQueuePlayerNode<Meta = unknown> {
                     this.queue.player.events.emit('playerSkip', this.queue, track);
                     this.queue.player.events.emit('playerError', this.queue, error, track);
                     this.queue.initializing = false;
-                    this.play(this.queue.tracks.dispatch(), { queue: false });
+                    const nextTrack = this.queue.tracks.dispatch();
+                    if (nextTrack) this.play( { queue: false });
```
Comment (skdhg) [inline packages/discord-player/src/Structures/GuildQueuePlayerNode.ts:399]:
```suggestion
                    if (nextTrack) this.play({ queue: false });
```

**Review by skdhg — APPROVED** [review]

File: packages/discord-player/src/Structures/GuildQueuePlayerNode.ts [hunk 2]
```diff
@@ -395,7 +395,8 @@ export class GuildQueuePlayerNode<Meta = unknown> {
                     this.queue.player.events.emit('playerSkip', this.queue, track);
                     this.queue.player.events.emit('playerError', this.queue, error, track);
                     this.queue.initializing = false;
-                    this.play(this.queue.tracks.dispatch(), { queue: false });
+                    const nextTrack = this.queue.tracks.dispatch();
+                    if (nextTrack) this.play({ queue: false });
```
Comment (DhakalYukesh) [inline packages/discord-player/src/Structures/GuildQueuePlayerNode.ts:399]: I think the better approach here would be
```typescript
if (nextTrack) {
    return this.play({ queue: false });
}
